# Generated by Django 5.1.7 on 2025-05-30 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jobs_posted',
            field=models.ManyToManyField(blank=True, related_name='posters', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='resumes.uploadedresume'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
