# Generated by Django 5.1.7 on 2025-05-30 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('application_start', models.DateField(default=django.utils.timezone.now)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Internship'), ('CT', 'Contract'), ('FL', 'Freelance')], default='FT', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, help_text='General description of the role', null=True)),
                ('required_skills', models.TextField(blank=True, help_text='Comma‑separated list or bullet text', null=True)),
                ('required_experience', models.TextField(blank=True, help_text='What level/years of experience is needed', null=True)),
                ('required_education', models.TextField(blank=True, help_text='Degrees or certifications required', null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
