# Generated by Django 5.1.7 on 2025-06-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_favoritejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='closed',
            field=models.BooleanField(default=False, help_text='Manually close this job posting'),
        ),
    ]
